In [3]:
#TRAINING IMAGES INPUT
import numpy as np
import pandas as pd

X = pd.read_csv("MNIST_data.csv")
X.describe

<bound method NDFrame.describe of        Unnamed: 0    0    1    2    3    4    5    6    7    8  ...    550  \
0               0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
1               1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
2               2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  255.0   
3               3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
4               4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
69995       69995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69996       69996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69997       69997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69998       69998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69999       69999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   

         551  552  553  554  

In [4]:
y = pd.read_csv("MNIST_labels.csv")
y = y.iloc[:,1]
y.describe

<bound method NDFrame.describe of 0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: 0, Length: 70000, dtype: int64>

In [5]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)

(56000, 561)
(14000, 561)


In [6]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Training the Random Forest model on the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,criterion="entropy",random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [8]:
#predicting the test set results using our model
y_pred = classifier.predict(X_test)

In [9]:
#Making the Confusion Matrix
sklearn.metrics import confusion_matrix, accuracy_score, f1_score,multilabel_confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1366    0    1    0    2    4    5    0    8    1]
 [   0 1561    6    3    3    1    1    3    1    1]
 [   4    3 1401    8    4    0    5    9    7    2]
 [   1    2   25 1358    0   16    1   15   13    4]
 [   1    0    1    1 1312    0    6    5    3   21]
 [   1    4    3   16    2 1179    8    0   10    8]
 [   8    3    1    0    5    9 1356    0    5    0]
 [   2    6   20    2   14    1    0 1391    2   20]
 [   2   10    4    6    4    4    6    1 1309   22]
 [   4    1    4   21   15    8    2   15    7 1284]]


0.9655

In [10]:
f1_score(y_test, y_pred,average="macro")

0.9651938573526694

In [ ]:
matrix = multilabel_confusion_matrix(y_test, y_pred)
print(matrix)