In [20]:
import numpy as np
import pandas as pd

In [21]:
X = pd.read_csv("MNIST_data.csv")
X.describe

<bound method NDFrame.describe of        Unnamed: 0    0    1    2    3    4    5    6    7    8  ...    550  \
0               0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
1               1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
2               2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  255.0   
3               3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
4               4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
69995       69995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69996       69996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69997       69997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69998       69998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69999       69999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   

         551  552  553  554  

In [22]:
y = pd.read_csv("MNIST_labels.csv")
y = y.iloc[:,1]
y.describe

<bound method NDFrame.describe of 0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: 0, Length: 70000, dtype: int64>

In [23]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)

(56000, 561)
(14000, 561)


In [24]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [25]:
# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0,multi_class="multinomial", solver='newton-cg')
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=0, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
#Predicting a new result
print(classifier.predict(sc.transform([X.iloc[69000,:]])))

[7]


In [27]:
y_pred = classifier.predict(X_test)
print(type(y_pred))
print(y_pred[-10:])
print(y_test[-10:])

<class 'numpy.ndarray'>
[8 5 7 9 0 3 2 7 4 6]
20774    8
10995    5
32930    9
61242    4
11451    0
29357    3
52488    2
9603     7
34949    4
25193    6
Name: 0, dtype: int64


In [28]:
#Making the Confusion Matrix
sklearn.metrics import confusion_matrix, accuracy_score, f1_score,multilabel_confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1332    0    8    2    3   16   15    5    6    0]
 [   0 1537    9    2    2    7    3    4   14    2]
 [  11   16 1283   18   23   10   19   19   40    4]
 [   6    8   48 1246    0   49    3   20   35   20]
 [   3    3   13    1 1240    4   15   15    5   51]
 [  11    5   14   37   15 1064   24    8   40   13]
 [  20    7   15    1   22   18 1292    3    9    0]
 [   6    8   19    5   16    6    1 1331    7   59]
 [   7   33   13   36   12   40   15    3 1193   16]
 [   4    9    5   16   57   13    1   45   12 1199]]


0.9083571428571429

In [29]:
f1_score(y_test, y_pred,average="macro")

0.906988883505479

In [ ]:
matrix = multilabel_confusion_matrix(y_test, y_pred)
print(matrix)