In [30]:
import numpy as np
import pandas as pd

X = pd.read_csv("MNIST_data.csv")
X.describe

<bound method NDFrame.describe of        Unnamed: 0    0    1    2    3    4    5    6    7    8  ...    550  \
0               0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
1               1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
2               2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  255.0   
3               3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
4               4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
69995       69995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69996       69996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69997       69997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69998       69998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69999       69999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   

         551  552  553  554  

In [31]:
y = pd.read_csv("MNIST_labels.csv")
y = y.iloc[:,1]
y.describe

<bound method NDFrame.describe of 0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: 0, Length: 70000, dtype: int64>

In [32]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)

(56000, 561)
(14000, 561)


In [33]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [34]:
#Training the SVM model
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [35]:
#predicting the test set results
y_pred = classifier.predict(X_test)

In [58]:
#Making the Confusion Matrix
sklearn.metrics import confusion_matrix, accuracy_score, f1_score,multilabel_confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1342    0    6    4    0   15   14    2    1    3]
 [   0 1549    9    5    2    3    0    4    8    0]
 [  14   16 1331   15   20    2   12   11   20    2]
 [   9   12   39 1283    1   42    0   10   27   12]
 [   5    4   14    3 1242    1    9   17    4   51]
 [  16    9   15   50    9 1071   17    2   24   18]
 [  17    5   25    1   24   16 1294    1    4    0]
 [   6    6   26   22   23    5    0 1339    2   29]
 [   6   25   16   30    9   22    8    3 1232   17]
 [   6    3   11   20   56    5    0   50    8 1202]]


0.9203571428571429

In [56]:
f1_score(y_test, y_pred, average="macro")

0.9192398319012435

In [57]:
matrix = multilabel_confusion_matrix(y_test, y_pred)
print(matrix)

[[[12534    79]
  [   45  1342]]

 [[12340    80]
  [   31  1549]]

 [[12396   161]
  [  112  1331]]

 [[12415   150]
  [  152  1283]]

 [[12506   144]
  [  108  1242]]

 [[12658   111]
  [  160  1071]]

 [[12553    60]
  [   93  1294]]

 [[12442   100]
  [  119  1339]]

 [[12534    98]
  [  136  1232]]

 [[12507   132]
  [  159  1202]]]
