In [3]:
import numpy as np
import pandas as pd

X = pd.read_csv("MNIST_data.csv")
X.describe

<bound method NDFrame.describe of        Unnamed: 0    0    1    2    3    4    5    6    7    8  ...    550  \
0               0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
1               1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
2               2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  255.0   
3               3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
4               4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
...           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
69995       69995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69996       69996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69997       69997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69998       69998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   
69999       69999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0   

         551  552  553  554  

In [4]:
y = pd.read_csv("MNIST_labels.csv")
y = y.iloc[:,1]
y.describe

<bound method NDFrame.describe of 0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: 0, Length: 70000, dtype: int64>

In [5]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)

(56000, 561)
(14000, 561)


In [6]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Training the Decision Tree model on the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [17]:
#Predicting a new result
print(classifier.predict(sc.transform([X.iloc[69000,:]])))

[7]


In [18]:
y_pred = classifier.predict(X_test)
print(type(y_pred))
#print(y_pred[-10:])
#print(y_test[-10:])

<class 'numpy.ndarray'>


In [22]:
#Making the Confusion Matrix
sklearn.metrics import confusion_matrix, accuracy_score, f1_score,multilabel_confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1281    1   15   13   12   22   13    4   15   11]
 [   1 1512   15    6    7    6    2   17   12    2]
 [  16    9 1224   34   19   17   32   37   40   15]
 [  10   12   35 1210    7   75    8   21   34   23]
 [   7    8   13    5 1176   12   15   16   29   69]
 [  15    4   12   51   10 1038   28    9   34   30]
 [  14    7   22   13   27   21 1248    1   24   10]
 [   6   11   41   19   16   13    4 1304    7   37]
 [   5   17   37   37   24   36   23   15 1126   48]
 [   6    3   11   28   72   32    5   35   31 1138]]


0.8755

In [23]:
f1_score(y_test, y_pred, average="macro")

0.873872764584976

In [24]:
matrix = multilabel_confusion_matrix(y_test, y_pred)
print(matrix)

[[[12533    80]
  [  106  1281]]

 [[12348    72]
  [   68  1512]]

 [[12356   201]
  [  219  1224]]

 [[12359   206]
  [  225  1210]]

 [[12456   194]
  [  174  1176]]

 [[12535   234]
  [  193  1038]]

 [[12483   130]
  [  139  1248]]

 [[12387   155]
  [  154  1304]]

 [[12406   226]
  [  242  1126]]

 [[12394   245]
  [  223  1138]]]
