In [1]:
#TRAINING IMAGES INPUT
import gzip
import numpy as np
import tensorflow as tf
import pandas as pd

f = gzip.open('train-images-idx3-ubyte.gz','r') #f is a file
image_size = 28  #originally 28
num_images = 60000

f.read(16)
buf = f.read(image_size * image_size * num_images)
data = np.frombuffer(buf, dtype=np.uint8).astype(np.float32)
data = data.reshape(num_images, image_size, image_size, 1)
print(data.shape)
print(type(data))

(60000, 28, 28, 1)
<class 'numpy.ndarray'>


In [2]:
#TRAINING LABELS INPUT
f = gzip.open('train-labels-idx1-ubyte.gz','r') #f is a file
f.read(8)
z = f.read() #z is a bytes #z has all the labels
labels = []
for i in z:
    labels.append(i)
labels = np.array(labels)
#len(bites)
print(labels.size)

60000


In [3]:
#TEST IMAGES 
f = gzip.open('t10k-images-idx3-ubyte.gz','r') #f is a file
image_size = 28  #originally 28
num_images = 10000

f.read(16)
buf = f.read(image_size * image_size * num_images)
data1 = np.frombuffer(buf, dtype=np.uint8).astype(np.float32)
data1 = data1.reshape(num_images, image_size, image_size, 1)
print(data1.shape)

(10000, 28, 28, 1)


In [4]:
#TEST LABELS
f = gzip.open('t10k-labels-idx1-ubyte.gz','r') #f is a file
f.read(8)
z = f.read() #z is a bytes #z has all the labels
labels2 = []
for i in z:
    labels2.append(i)
labels2 = np.array(labels2)
len(labels2)

10000

In [5]:
#want to combine test and train data
#let's first combine the labels #bites
labels = labels.tolist()
len(labels)
labels2 = labels2.tolist()
len(labels2)
labels = labels + labels2
print(len(labels))

70000


In [6]:
#combining data arrays
data = data.tolist()
print("sup")
data1 = data1.tolist()
print("hi")
data = data + data1
print("hello")
data = np.array(data)
print(data.shape)

sup
hi
hello
(70000, 28, 28, 1)


In [7]:
#manipulating data array so that each row is a picture and columns are the bits
#print(data[0,:,:].shape)
#print(data[3,4:24,:,0]) #data[i,:,:,0] return ith matrix with blank header and footer
#data[i,4:-4,:,0] return ith matrix without footers

vectors = []
for matrix in range(70000):#70000
    vector = []
    for row in range(4,24):
        for col in range(0,28):
            vector.append(data[matrix,row,col,0])
    #print(vector)
    
    vectors.append(vector)
print("vectors ",end="")
print(len(vectors))
vectors = np.array(vectors)
print(vectors.shape)

vectors 70000
(70000, 560)


In [8]:
#Splitting the dataset into the Training set and Test set
X = data
y = labels
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(vectors, y, test_size = 0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)

(56000, 560)
(14000, 560)


In [9]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
#Training the SVM model
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [12]:
#predicting the test set results
y_pred = classifier.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1344    0    6    4    0   13   13    2    2    3]
 [   0 1552    9    5    2    2    0    2    8    0]
 [  13   12 1338   15   18    3   13   10   19    2]
 [   7   11   41 1283    1   42    0   10   27   13]
 [   5    4   15    2 1243    1   10   16    5   49]
 [  17    7   16   48    9 1074   15    2   24   19]
 [  15    5   25    1   21   18 1296    2    4    0]
 [   6    7   24   20   23    6    0 1341    2   29]
 [   5   24   17   30    9   24    8    2 1229   20]
 [   7    3   11   20   57    5    0   48    7 1203]]


0.9216428571428571

In [14]:
#92.2%
#[[1344    0    6    4    0   13   13    2    2    3]
 #[   0 1552    9    5    2    2    0    2    8    0]
 #[  13   12 1338   15   18    3   13   10   19    2]
 #[   7   11   41 1283    1   42    0   10   27   13]
 #[   5    4   15    2 1243    1   10   16    5   49]
 #[  17    7   16   48    9 1074   15    2   24   19]
 #[  15    5   25    1   21   18 1296    2    4    0]
 #[   6    7   24   20   23    6    0 1341    2   29]
 #[   5   24   17   30    9   24    8    2 1229   20]
 #[   7    3   11   20   57    5    0   48    7 1203]]